version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: dummy_secret_key_base
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: instaclone_production
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  db_data:
